appstager/urls.py
from django.conf.urls import url

from . import views

app_name = 'appstager'

urlpatterns = [
    url(r'^$', views.start, name='start'),
    url(r'^index/', views.index, name='index'),
    url(r'^(?P<show_id>[0-9]+)/$', views.showActions, name='showActions'),
    url(r'^choice/',views.choice,name='choice'),
    url(r'^addshow/',views.show,name='show'),
	# AJAX URLs
	url(r'^getAction$', views.getAction, name='getAction'),
	url(r'^createAction/(?P<actType>[\w]+)$', views.createAction, name='createAction'),
	url(r'^updateActionUp/(?P<order>[\w]+)$', views.updateActionUp, name='updateActionUp'),
	url(r'^updateActionDown/(?P<order>[\w]+)$', views.updateActionDown, name='updateActionDown'),
	url(r'^activeAction/(?P<name>[\w]+)$', views.activeAction, name='activeAction'),
	url(r'^submitAction$', views.submitAction, name='submitAction')
]

stager/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    url(r'^', include('appstager.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
]

'''if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
'''

appstager/models.py
from django.db import models
import uuid
from datetime import timedelta

class Theater(models.Model):
	name = models.CharField(max_length = 100,help_text = "Name of the Theater", unique = True)

	def __str__(self):
		return (str(self.name))

class Show(models.Model):
	name = models.CharField(max_length = 100, help_text = "Name of the Show", unique = True)
	theater = models.ForeignKey(Theater, on_delete=models.CASCADE, null=True)
	number_of_seats = models.IntegerField(null=True, help_text = "Input the number of seats this theater has")
	director=models.CharField(max_length=100, help_text = "Director of this show.")

	def __str__(self):
		return (str(self.name))


class Action(models.Model):
	show = models.ForeignKey(Show, on_delete=models.CASCADE)

	ACTION_TYPE = (
        ('Vibrate', 'Vibrate'),
        ('Background', 'Background'),
        ('Sound', 'Sound'),
        ('Image', 'Image'),
        ('Video', 'Video')
    )
	name = models.CharField(max_length = 50,help_text = "Name of the action", unique = True)
	description = models.TextField(max_length = 200, help_text = "Description of the action")
	action_type = models.CharField(max_length = 50, choices = ACTION_TYPE, help_text = "Name of the action type")
	order = models.IntegerField(null=True, help_text = "Order of the action in the show (from QLab)")

	duration = models.DurationField(default=timedelta, help_text = "Duration of the action (HH:MM:SS)")

	redValue = models.CharField(max_length = 3, help_text = "The value of the color red that should be used", default="0")
	greenValue = models.CharField(max_length = 3, help_text = "The value of the color green that should be used", default="0")
	blueValue = models.CharField(max_length = 3, help_text = "The value of the color blue that should be used", default="0")

    
	def __str__(self):
		return (str(self.action_type) + '~~~' + str(self.name) + '~~~' + str(self.description) + '~~~' + str(self.order) + '~~~' + str(self.duration) + '~~~' + str(self.redValue) + '~~~' + str(self.greenValue) + '~~~' + str(self.blueValue))

appstager/forms.py
from django import forms
from appstager.models import Action
from appstager.models import Show, Theater
from django.forms import ModelForm, Textarea
from django.forms import ModelForm

'''class ActionForm(ModelForm):
	class Meta:
		model=Action
		#fields=['name','description']
		fields = '__all__'
		#exclude=['id']

		#help_texts={
		#'name':None,
		#'description':None,
		#}
'''
class CueForm(forms.Form):
	name=forms.CharField(label='Name',max_length=100)
	description=forms.CharField(label='Description',max_length=100)
	sequenceNum=forms.IntegerField(label='sequencenum')
	showId=forms.IntegerField(label='showid')

class ShowForm(ModelForm):
	class Meta:
		model=Show
		fields=['name','director']
		exclude=['help_text']
		error_messages = {
			'name': {
				'unique': ("The name of each show must be unique."),
			},
		}






class ActionForm(ModelForm):
	class Meta:
		model = Action
		fields = ['show','action_type', 'name', 'description', 'order', 'duration']
		error_messages = {
			'name': {
				'unique': ("The name of each action must be unique."),
			},
		}

appstager/views.py
import requests
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.core import serializers  # Convert query list to string
from django.http import HttpResponse # Return a basic HTTP response
from django.http import JsonResponse # Return a basic JSON response
from appstager.capstone import sendcapstone
from appstager.models import Action,Show, Theater

from .forms import ActionForm,ShowForm


def start(request):
	context = {'user':request.user}
	return render(request, "appstager/login.html",context)


def index(request):
	action = Action.objects.all().order_by('order')
	context = { 'action':action }
	#send the Cue to the capstone through HTTP Request
	if "Send" in request.POST:
			context['server_response']=(sendcapstone(action))

	
	return render(request, "appstager/planner.html", context)

#added a shows function which lists all the shows and allows the user to add a show.
def show(request):
	shows=Show.objects.all()
	context={'shows':shows}
	if request.method=="POST":
		form=ShowForm(request.POST)
		if form.is_valid():
			form.save()
			try:
				requests.post('http://localhost:4000/shows?name='+str(request.POST['name'])+'&director='+str(request.POST['director']))
				context['server_response']="Show successfuly Added!"   #server_response contains the message if the POST/GET request was successful or not! 
				
			except requests.exceptions.RequestException:
				context['server_response']= "Error with Qlab API"
	else:
		form=ShowForm()
	
	context['form']=form
	return render(request,"appstager/shows.html",context)

# AJAX METHODS
def getAction(request):
	#Needs fixing
	#show_id is missing
	reqshow = Show.objects.get(id=show_id)
	print(reqshow)
	actionDataOrder = Action.objects.order_by('order').filter(show=reqshow)
	return render(request, 'appstager/actionList.html', {'actionData':actionDataOrder})

def createAction(request, actType):
	print("Showing form in the properties panel")

	data = {'action_type': actType}
	form = ActionForm(data)

	context = { 'form':form }
	return render(request, "appstager/createAction.html", context)

def submitAction(request):
	# We need to return something to report that the operation was successful
	if request.method == 'POST':


		form = ActionForm(request.POST)
		if form.is_valid():
			form.save()
			msg = "Add a new action!"
			return HttpResponse("success")
	msg = "There was an error in for submission"
	return HttpResponse(msg)

def updateActionUp(request, order):
	# This will create an object with the name passed to it as POST data
	print("Updating action")

	orderNum = int(order)

	# Get the type of foreign key from the argument
	action1 = Action.objects.get(order = orderNum)
	action2 = Action.objects.get(order = orderNum - 1)
	action1.order = orderNum - 1
	action2.order = orderNum
	action1.save()
	action2.save()

	# We need to return something to report that the operation was succesful
	return HttpResponse("success");

def updateActionDown(request, order):
	# This will create an object with the name passed to it as POST data
	print("Updating action")

	orderNum = int(order)

	# if last item, do nothing
	if orderNum == Action.objects.all().count():
		print("No changes made")
		return HttpResponse("success")

	# Get the type of foreign key from the argument
	action1 = Action.objects.get(order = orderNum)
	action2 = Action.objects.get(order = orderNum + 1)
	action1.order = orderNum + 1
	action2.order = orderNum
	action1.save()
	action2.save()

	# We need to return something to report that the operation was succesful
	return HttpResponse("success");


def activeAction(request, name):
	print("THIS IS THE PRINT!!")
	print(name)
	data = Action.objects.get(name = name)
	return HttpResponse(data, content_type='text/plain') # Return it as json http response

def showActions(request, show_id):
	reqshow = Show.objects.get(id=show_id)
	print(reqshow)
	action = Action.objects.order_by('order').filter(show=reqshow)
	print("These are the actions found: "+ str(action))
	context = { 'action':action }
	#send the Cue to the capstone through HTTP Request
	if "Send" in request.POST:
			context['server_response']=(sendcapstone(action))

	
	return render(request, "appstager/planner.html", context)

def choice(request):
	availableTheaters = Theater.objects.all().order_by('name')

	if request.POST:
		if(request.POST.get("theatername","") !='' ):
			selectedTheater = Theater.objects.get(id=request.POST.get("theatername",""))
			print(selectedTheater)
			availableShows = Show.objects.filter(theater=selectedTheater)
			print(availableShows)
		try:
			availableShows = Show.objects.filter(theater=selectedTheater)
		except:
			availableShows = {}
		if(request.POST.get("showname","") !='' ):
			show_id=request.POST.get("showname","")
			return redirect('/' + show_id)
	else:
		availableShows = {}

	print(availableShows)
	context = {'theaters': availableTheaters, 'shows': availableShows}
	return render(request, "appstager/choice.html", context)

appstager/templates/appstager/actionList.html
				{% for act in actionData %}
            	<li class="itemButton" id="event{{ forloop.counter }}" title="{{act.name}}">
            		<label id="orderLabel">{{act.order}}</label> &nbsp;
            		<label id="actionLabel">{{act.action_type}}</label> &nbsp;
            		<label id="nameLabel">{{act.name}}</label> &nbsp;
            		<label id="durationLabel">{{act.duration}}</label> &nbsp;
            		<i class="fa fa-bars bars" aria-hidden="true"></i>
            		<i class="fa fa-arrow-down arrow" aria-hidden="true"></i>
            		<i class="fa fa-arrow-up arrow" aria-hidden="true"></i>
            		<div class="panel">
            			<label><b>Name: </b></label>
            			{{act.name}}<br />
                       	<label><b>Description: </b></label>
                       	{{act.description}} <br />
                  	</div>
            	</li>
            	{% endfor %}
            	<li class="addNewAction">
					<div id="addLabel">
						Add...
					</div>
            		<div id="newAction" class="sidenav2">
						<i class="fa fa-bell addActionTypeA" aria-hidden="true" title="Vibrate"></i>
						<i class="fa fa-square addActionTypeA" aria-hidden="true" title="Background"></i>
						<i class="fa fa-volume-up addActionTypeA" aria-hidden="true" title="Sound"></i>
						<i class="fa fa-picture-o addActionTypeA" aria-hidden="true" title="Image"></i>
						<i class="fa fa-film addActionTypeA" aria-hidden="true" title="Video"></i>
  					</div>
            	</li>

appstager/templates/appstager/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <title>Stager | St. Olaf College</title>
        <meta name="author" content="Deepak Shah, Luke Zimmerman, Hugo Valent">
        <meta name="description" content="Theater production planning application">
        <meta name="keywords" content="theater, production, technology, planning, hipercic">

        <link rel="stylesheet" type="text/css" href="{% static 'appstager/base.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'appstager/theater.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'appstager/nav.css' %}" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">

    </head>
    

    <body>	
	{% if user.is_authenticated %}
		{% include "appstager/nav.html" %}
		{% block main-content %}
		{% endblock %}
	{% else %}
		{% block login-block %}
		{% endblock %}
	{% endif %}

    </body>
</html>

appstager/templates/appstager/capstone.html
{% extends "appstager/base.html" %}

{% block main-content %}

{% load staticfiles %}
<p> Hello world</p>
<script src="{% static 'appstager/jquery-3.2.1.js' %}"></script>

	<div id="myModal" class="modal">
  		<!-- Modal content -->
  		<div class="modal-content">
    		<span class="closeModal">&times;</span>
    		<p>Successfully sent!</p>
  		</div>
	</div>
{% endblock %}

appstager/templates/appstager/choice.html
{% extends "appstager/base.html" %}
{% block main-content %}
{% load staticfiles %}

<h3>Please Select a Theater</h3>


{% if shows %}
<form action='/choice/' method='post'>
	{% csrf_token %}
	{% for show in shows %}
		<input type="radio" name="showname" value= "{{show.id}}" > {{ show.name }}<br>
	{% endfor %}
<input type='submit' name='Select a Show' value='Select a Show'>
</form>
{% else %}
<form action='/choice/' method='post'>
	{% csrf_token %}
	{% for theater in theaters %}
		<input type="radio" name="theatername" value= "{{theater.id}}" > {{ theater.name }}<br>
	{% endfor %}
<input type='submit' name='Select Theater' value='Select a Theater'>
</form>
<h3> No Theater Selected </h3>
{% endif %}
{% endblock %}

appstager/templates/appstager/createAction.html
		<form id="newActionForm" action="/submitAction" method="post">
			{% csrf_token %}
			{% for field in form %}
			{{ field.label_tag }} <br />
			<div class="helpText"> {{ field.help_text }} </div>
			{{ field }}<br />
			{% endfor %}
			<input type="submit" name="actionVal" value="Save" />
		</form>

appstager/templates/appstager/login.html
{% load static %}

{% block login-block %}
<head>
	<title>Accounts</title>
	<link rel="stylesheet" type="text/css" href="{% static 'appstager/login.css' %}" />
	<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
<head>

<body>
	{% if user.is_authenticated %}
	<h3>Stager</h3>
	<div id="user-tools">
	{% if user.is_admin or user.is_superuser %}
		<a href="/admin">
			<div class="tile">
				Admin
			</div>
		</a>
	{%endif%}
		<a id="showTile" href="{% url 'appstager:choice' %}">
			<div class="tile">
				Planner
			</div>
		</a>
		<a id="theaterTile" href="">
			<div class="tile">
				Theater
			</div>
		</a>
		<a id="logoutTile" href="/accounts/logout" >
			<div class="tile">
				Logout
			</div>
		</a>
	</div>
	{% else %}
	<h3>Stager</h3>
	<div class="loginPanel">
		<p>Please login to continue.</p>
		<div id="user-tools-login">
			<a id="google_login" href="/accounts/google/login" class="appstager-nav-item">
				<div id="googleLogin"></div>
			</a>
		</div>
	</div>
	{% endif %}
<body>
{% endblock %}

appstager/templates/appstager/nav.html
<div class="topnav" id="StagerNav">
	<div>Stager</div>
  	<a id="propertyBtn">Properties</a>
  	<a id="theaterBtn">Theater</a>
  	<a id="simulationBtn">Simulation</a>
  	<a id="helpBtn">Help</a>
</div>

appstager/templates/appstager/planner.html
{% extends "appstager/base.html" %}

{% block main-content %}

{% load staticfiles %}

<script src="{% static 'appstager/jquery-3.2.1.js' %}"></script>

        <script>
            // toggle the menu using on() for the AJAX loaded content
        	$(document).on('click','.action .itemButton .bars', function(e) {
     			$(this).parent().find('.panel').slideToggle('500');  
			});

        	// toggle the action type icons
			$(document).on('mouseenter mouseleave', '.addNewAction', function(e) {
				$('#newAction').stop().toggle();
				$('#addLabel').stop().toggle();
			});

        	// open the side navigation panel
        	$(document).ready(function() {
        		// open the side navigation panel
                $("#openNav").click(function() {
                    if($(".sidenav").css("width") == "0px") {
                        $(".sidenav").css("width", "150px");
                    } else {
                        $(".sidenav").css("width", "0px");
                    }
                });

                // close the side navigation panel
                $(".closebtn").click(function() {
                	$(".sidenav").css("width", "0px");
                });

				// close the side navigation on click outside
				$(document).mouseup(function(e) {
					var container = $('.sidenav');

					// if the target of the click isn't the container nor a descendant of the container
					if (!container.is(e.target) && container.has(e.target).length === 0) {
						container.css("width", "0px");
					}
				});

                // open the list properties
                $("#propertyBtn").click(function() {
                	$('.tabcontent').each(function() {
    					$("#" + this.id).hide();
					});
					$('#StagerNav a').removeClass('active');
					$(this).addClass('active')
                	$("#properties").show();
                });

                // open the theater visual
                $("#theaterBtn").click(function() {
                	$('.tabcontent').each(function() {
    					$("#" + this.id).hide();
					});
					$('#StagerNav a').removeClass('active');
					$(this).addClass('active')
                	$("#theaterContainer").show();
                });
            });
        </script>
    </head>
    
    <body>
    <div class="leftBar">
        <div class="action" ondragover="allowDrop(event)" ondrop="drop(event)">
            <h3>Actions</h3>
           	<i id="openNav" class="fa fa-plus"></i>
            <div id="mySidenav" class="sidenav">
		  		<a href="javascript:void(0)" class="closebtn">&times;</a>
		  		<a class="addActionType">
		  			<i class="fa fa-bell" aria-hidden="true" title="Vibrate"></i>
		  			Vibrate
		  		</a>
		  		<a class="addActionType">
		  			<i class="fa fa-square" aria-hidden="true" title="Background"></i>
		  			Background
		  		</a>
		  		<a class="addActionType">
            		<i class="fa fa-volume-up" aria-hidden="true" title="Sound"></i>
		  			Sound
		  		</a>
		  		<a class="addActionType">
            		<i class="fa fa-picture-o" aria-hidden="true" title="Image"></i>
		  			Image
		  		</a>
		  		<a class="addActionType">
		  			<i class="fa fa-film" aria-hidden="true" title="Video"></i>
		  			Video
		  		</a>
			</div>
            <ul class="action_list">
            	{% for act in action %}
            	<li class="itemButton" title="{{act.name}}">
            		<label id="orderLabel">{{act.order}}</label> &nbsp;
            		<label id="actionLabel">{{act.action_type}}</label> &nbsp;
            		<label id="nameLabel">{{act.name}}</label> &nbsp;
            		<label id="durationLabel">{{act.duration}}</label> &nbsp;
            		<i class="fa fa-bars bars" aria-hidden="true"></i>
            		<i class="fa fa-arrow-down arrow" aria-hidden="true"></i>
            		<i class="fa fa-arrow-up arrow" aria-hidden="true"></i>
            		<div class="panel">
            			<label><b>Name: </b></label>
            			{{act.name}}<br />
                       	<label><b>Description: </b></label>
                       	{{act.description}} <br />
                  	</div>
            	</li>
            	{% endfor %}
            	<li class="addNewAction">
					<div id="addLabel">
						Add...
					</div>
            		<div id="newAction" class="newAction">
						<i class="fa fa-bell addActionTypeA" aria-hidden="true" title="Vibrate"></i>
            			<i class="fa fa-square addActionTypeA" aria-hidden="true" title="Background"></i>
            			<i class="fa fa-volume-up addActionTypeA" aria-hidden="true" title="Sound"></i>
            			<i class="fa fa-picture-o addActionTypeA" aria-hidden="true" title="Image"></i>
            			<i class="fa fa-film addActionTypeA" aria-hidden="true" title="Video"></i>
  					</div>
            	<li>
            </ul>
            <div id="sendCap">
                <form action="" method="POST">{% csrf_token %}

            	<input type="submit" name="Send" value="Send to Qlab"/>
            </form>
            </div>
            <p> {{server_response}}</p>
        </div>
    </div>
    <div class="viz">
        <h3>Visualization</h3>
        <div class="tabcontent" id="newActionForm">

        </div>
        <div class="tabcontent" id="properties">
        	<div id="type">
        		<h5>Action Type:</h5>
        	</div>
        	<div id="name">
        		<h5>Name:</h5>
        	</div>
        	<div id="description">
        		<h5>Description:</h5>
        	</div>
        	<div id="order">
        		<h5>Order:</h5>
        	</div>
        	<div id="duration">
        		<h5>Duration:</h5>
        	</div>
			<div id="red">
				<h5>Red:</h5>
        	</div>
			<div id="green">
				<h5>Green:</h5>
        	</div>
        	<div id="blue">
        		<h5>Blue:</h5>
        	</div>
        </div>
        <div class="tabcontent" id="theaterContainer">
        	{% include "appstager/theater.html" %}
        </div>
    </div>

    <!-- The Modal -->
	<div id="myModal" class="modal">
  		<!-- Modal content -->
  		<div class="modal-content">
    		<span class="closeModal">&times;</span>
    		<p>Successfully created an action!</p>
  		</div>
	</div>


    </body>
	<script type="text/javascript" src="{% static 'appstager/jquery.cookie.js' %}"></script>

    <script type="text/javascript">
	$(function() {
		// runs once the page loads

		// CSRF block for AJAX calls
	    var csrftoken = $.cookie('csrftoken');
	    function csrfSafeMethod(method) {
		    // these HTTP methods do not require CSRF protection
		    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
		}
		$.ajaxSetup({
		    beforeSend: function(xhr, settings) {
		        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
		            xhr.setRequestHeader("X-CSRFToken", csrftoken);
		        }
		    }
		});
		/// End CSRF block

		// Add an action form for a specific action type
		$('.addActionType').click(function(e) {
            // find the inner <i> element
            actType = $(this).children().attr('title');
            // console.log(actType);

            // pass the action type as an argument to views.py
            $('#newActionForm').load(
            	"{% url 'appstager:createAction' actType='TEMP' %}".replace(/TEMP/, actType.toString()),
            	function() {
            		// show the panel after AJAX finishes loading
		            $('.tabcontent').each(function() {
		            	$("#" + this.id).hide();
		            });
		            $('#StagerNav a').removeClass('active');
		            $("#newActionForm").show();
            	});
		});

		// Add an action form for a specific action type
		$(document).on('click', '.addActionTypeA', function(e) {
            // find the title of the <i> element
            actType = $(this).attr('title');
            console.log(actType);

            // pass the action type as an argument to views.py
            $('#newActionForm').load(
            	"{% url 'appstager:createAction' actType='TEMP' %}".replace(/TEMP/, actType.toString()),
            	function() {
            		// show the panel after AJAX finishes loading
		            $('.tabcontent').each(function() {
		            	$("#" + this.id).hide();
		            });
		            $('#StagerNav a').removeClass('active');
		            $("#newActionForm").show();
            	});
		});

    	// when a list item is clicked, update the "active" action and return in the context
    	$(document).on('click', '.itemButton', function(e) {
    		// get the name of the action
    		name = $(this).attr('title');
    		console.log(name);
    		// pass the action name as an argument to views.py
			$.post("{% url 'appstager:activeAction' name='TEMP' %}".replace(/TEMP/, name.toString()), getCallback).fail(addFail);
			$('.itemButton').removeClass('active')
			$(this).addClass('active')
    	});

    	function getCallback(data) {
			console.log(data)
			$('.actionAttrib').empty()
			// populate in most recent order
			var idNames = ["type", "name", "description", "order", "duration", "red", "green", "blue"];
			var arr = data.split('~~~');
			for(var i = 0; i <= arr.length - 1; i++) {
				$('#' + idNames[i]).append("<p class=\"actionAttrib\">" + arr[i] + "</p>")
			}
		}

    	function addCallback(data) {
			console.log(data)
			// update the action list on the page
			getActions();
		}
		function addFail(failMessage) {
			console.log(failMessage.responseText)
		}

		// get the actions for the page
		function getActions(item_num) {
    	    console.log("update actions")
    	    $('.action_list').load(
            "{% url 'appstager:getAction' %}"
    	)};

   		// switch the order using on() for the AJAX loaded content
    	$(document).on('click','.action .itemButton .fa-arrow-up', function(e) {
 			// get the order of the button
 			orderStr = $(this).parent().attr('id')
 			order = Number(orderStr.substr(orderStr.length - 1))

 			// produce an alert and return if top item
 			if(order == 1) {
 				alert("Top element: cannot move up");
 				return;
 			}

 			// pass the action type as an argument to views.py
			$.post("{% url 'appstager:updateActionUp' order='TEMP' %}".replace(/TEMP/, order.toString()), addCallback).fail(addFail); 
		});

		// submit the new action form using AJAX
		$(document).on('submit', '#newActionForm', function(e) {
			e.preventDefault();
			$.ajax({
				type:'POST',
				url:"{% url 'appstager:submitAction' %}",
				data: $(this).serialize(),
				success: function() {
					getActions();
					$("#newActionForm").hide();

					// display the modal
					$('#myModal').css('display', 'block');

					return;
				},
				error: function() {
					return;
				}
			});
		});

		// when the user clicks on <span>, close the modal
		$(".closeModal").click(function() {
			$('#myModal').css('display', 'none');
        });

		// switch the order using on() for the AJAX loaded content
    	$(document).on('click','.action .itemButton .fa-arrow-down', function(e) {
 			orderStr = $(this).parent().attr('id');
 			order = Number(orderStr.substr(orderStr.length - 1));

 			// pass the action type as an argument to views.py
			$.post("{% url 'appstager:updateActionDown' order='TEMP' %}".replace(/TEMP/, order.toString()), addCallback).fail(addFail);   
		});

		// Get objects when the page first loads
		getActions()
	});
	</script>
{% endblock %}

appstager/templates/appstager/shows.html
{% extends "appstager/base.html" %}

{% block main-content %}

{% load staticfiles %}

<h3>Existing Shows</h3>
<ul class="show_list">
	{% for show in shows %}
	<li class="itemButton">
		<label id="nameLabel">{{show.name}}</label> &nbsp;
		<label id="directorLabel">{{show.director}}</label> &nbsp;
	</li>
	{% endfor %}
</ul>

<h3>Create Show</h3>
<form action='' method='post'>
	{% csrf_token %}
	{% for field in form %}
	{{ field.label_tag }} <br />
	<div class="helpText"> {{ field.help_text }} </div>
	{{ field }}<br />
	{% endfor %}
<input type='submit' name='Add' value='Add a show'>
</form>
{{server_response}}
{% endblock %}